# Generated by Django 4.0.2 on 2022-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
