# Generated by Django 4.0.2 on 2022-05-06 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gur', '0002_auto_20220203_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courieraccount',
            name='tel_num',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Будь ласка, вкажіть правильний номер телефону.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurantadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='tel_num',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Будь ласка, вкажіть правильний номер телефону.', regex='^[0-9]*$')]),
        ),
    ]
